// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/go-playground/validator/v10"
	"github.com/iruldev/mini-wallet/engine/rest/controller"
	"github.com/iruldev/mini-wallet/engine/rest/transformer"
	"github.com/iruldev/mini-wallet/src/database"
	"github.com/iruldev/mini-wallet/src/repository"
	"github.com/iruldev/mini-wallet/src/service"
	"github.com/iruldev/mini-wallet/src/token"
	"github.com/spf13/viper"

	_ "github.com/iruldev/mini-wallet/src/config"
)

// Injectors from injector.go:

func InitializeWalletControllerREST() (controller.WalletController, error) {
	validate := validator.New()
	string2 := JwtSecretKey()
	maker := token.NewJWTMaker(string2)
	db := database.GetDB()
	walletRepository := repository.NewWalletRepository(db)
	walletService := service.NewWalletService(maker, walletRepository)
	walletTransformer := transformer.NewWalletTransformer()
	walletController := controller.NewWalletController(validate, walletService, walletTransformer)
	return walletController, nil
}

// injector.go:

func JwtSecretKey() string {
	return viper.GetString("JWT_SECRET_KEY")
}
