// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/go-playground/validator/v10"
	"github.com/iruldev/mini-wallet/engine/rest/controller"
	"github.com/iruldev/mini-wallet/engine/rest/transformer"
	"github.com/iruldev/mini-wallet/src/database"
	"github.com/iruldev/mini-wallet/src/repository"
	"github.com/iruldev/mini-wallet/src/service"
	"github.com/iruldev/mini-wallet/src/token"
	"github.com/spf13/viper"
)

import (
	_ "github.com/iruldev/mini-wallet/src/config"
)

// Injectors from injector.go:

func InitializeWalletService() service.WalletService {
	string2 := JwtSecretKey()
	maker := token.NewJWTMaker(string2)
	db := database.GetDB()
	walletRepository := repository.NewWalletRepository(db)
	walletService := service.NewWalletService(maker, walletRepository)
	return walletService
}

func InitializeWalletControllerREST() (controller.WalletController, error) {
	validate := validator.New()
	walletService := InitializeWalletService()
	walletTransformer := transformer.NewWalletTransformer()
	walletController := controller.NewWalletController(validate, walletService, walletTransformer)
	return walletController, nil
}

func InitializeTransactionControllerREST() (controller.TransactionController, error) {
	validate := validator.New()
	db := database.GetDB()
	transactionRepository := repository.NewTransactionRepository(db)
	transactionService := service.NewTransactionService(transactionRepository)
	transactionTransformer := transformer.NewTransactionTransformer()
	walletService := InitializeWalletService()
	transactionController := controller.NewTransactionController(validate, transactionService, transactionTransformer, walletService)
	return transactionController, nil
}

// injector.go:

func JwtSecretKey() string {
	return viper.GetString("JWT_SECRET_KEY")
}
