// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/go-playground/validator/v10"
	"github.com/iruldev/mini-wallet/engine/rest/controller"
)

// Injectors from injector.go:

func InitializeWalletControllerREST() (controller.WalletController, error) {
	validate := validator.New()
	walletController := controller.NewWalletController(validate)
	return walletController, nil
}
